FROM kasmweb/core-ubuntu-focal:1.13.1
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install

WORKDIR $HOME

######### Customize Container Here ###########

# Set Anaconda environment
ENV CONDA_DIR /opt/anconda3
ENV PATH $CONDA_DIR/bin:$PATH

# Install Anaconda
RUN cd /tmp/ && \
    wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh && \
    chmod +x Anaconda3-2023.07-1-Linux-x86_64.sh && \
    ./Anaconda3-2023.07-1-Linux-x86_64.sh -b -p ${CONDA_DIR} && \
    rm -r Anaconda3-2023.07-1-Linux-x86_64.sh

# Add Conda to Global Path
ENV PATH="$CONDA_BIN:$PATH"
RUN echo 'export PATH="$PATH"' >> /etc/bash.bashrc

# Setup Anaconda User profile
RUN conda update -n base conda && \
    conda update --all && \
    conda clean --all && \
    conda config --set ssl_verify /etc/ssl/certs/ca-certificates.crt && \
    conda install pip && \
    mkdir -p /home/kasm-user/.pip && \
    chown -R 1000:1000 ${CONDA_DIR} ${HOME}/.conda/ && \
    conda install -y jupyter

# Define source location
ENV SRC ./src/ubuntu/install

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    SHELL_SCRIPTS="tools/install_tools.sh \
                  chrome/install_chrome.sh \
                  vs_code/install_vs_code.sh \
                  cleanup/cleanup.sh"

# Copy install scripts
COPY $SRC $INST_SCRIPTS

# Run installations
RUN \
  for SCRIPT in $SHELL_SCRIPTS; do \
    bash ${INST_SCRIPTS}/${SCRIPT}; \
  done && \
  rm -Rf ${INST_SCRIPTS}

########## End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000